package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"

	"github.com/nosuta/godash/v2/internal/hotlayout"
	godashpb "github.com/nosuta/godash/v2/pb"
)

func main() {
	var flags flagSet
	opts := protogen.Options{
		ParamFunc: flags.Set,
	}
	opts.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f, flags.corePkg)
		}
		return nil
	})
}

type flagSet struct {
	corePkg string
}

func (f *flagSet) Set(name, value string) error {
	switch name {
	case "core_pkg":
		f.corePkg = value
	}
	return nil
}

func generateFile(gen *protogen.Plugin, file *protogen.File, corePkg string) {
	pushMessages := collectPushMessages(file)
	hasPush := len(pushMessages) > 0

	var normalServices, reverseServices []*protogen.Service
	for _, svc := range file.Services {
		if strings.HasSuffix(string(svc.Desc.Name()), "ReverseService") {
			reverseServices = append(reverseServices, svc)
		} else {
			normalServices = append(normalServices, svc)
		}
	}

	if len(normalServices) == 0 && len(reverseServices) == 0 && !hasPush {
		return
	}

	if corePkg == "" {
		corePkg = "github.com/nosuta/godash/v2/pb"
	}

	filename := file.GeneratedFilenamePrefix + ".godash.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-godash. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	alias := "core"

	g.P("import (")
	needsContext := len(normalServices) > 0 || len(reverseServices) > 0
	if needsContext {
		g.P(`	"context"`)
	}
	if hasPush {
		g.P(`	"fmt"`)
	}
	g.P()
	g.P(`	core "`, corePkg, `"`)
	g.P(")")
	g.P()

	for _, svc := range normalServices {
		generateNormalService(g, svc, alias)
	}

	for _, svc := range reverseServices {
		generateReverseService(g, svc, alias)
	}

	if hasPush {
		emitPushHelpers(g, pushMessages, alias)
	}

	hot := collectHotMethods(normalServices)
	if len(hot) > 0 {
		generateHotFile(gen, file, hot)
	}
}

// isHot reports whether the method carries the `(godash.hot) = true` option.
func isHot(m *protogen.Method) bool {
	opts := m.Desc.Options()
	if opts == nil {
		return false
	}
	v, _ := proto.GetExtension(opts, godashpb.E_Hot).(bool)
	return v
}

// hotMethod is a unary method marked hot whose request and response messages
// are both packable.
type hotMethod struct {
	service *protogen.Service
	method  *protogen.Method
	req     hotlayout.Layout
	resp    hotlayout.Layout
}

// collectHotMethods returns the packable hot methods for the given services.
// Methods that are marked hot but not packable (or streaming) are skipped:
// they keep the normal protobuf envelope path.
func collectHotMethods(services []*protogen.Service) []hotMethod {
	var out []hotMethod
	for _, svc := range services {
		for _, m := range svc.Methods {
			if m.Desc.IsStreamingClient() || m.Desc.IsStreamingServer() {
				continue
			}
			if !isHot(m) {
				continue
			}
			req, err := hotlayout.Compute(m.Input.Desc)
			if err != nil {
				continue
			}
			resp, err := hotlayout.Compute(m.Output.Desc)
			if err != nil {
				continue
			}
			out = append(out, hotMethod{service: svc, method: m, req: req, resp: resp})
		}
	}
	return out
}

// generateHotFile emits <file>.hot.go, native-only (`//go:build !js`), holding
// the packed-struct unpack/pack functions for each hot method. They are called
// from the generated packed-struct exports through the rpc.HotInvoke
// dispatcher. Keeping this file off the web build means the web worker never
// compiles the unsafe pointer code.
func generateHotFile(gen *protogen.Plugin, file *protogen.File, hot []hotMethod) {
	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+".hot.go", file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-godash. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("//go:build !js")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	g.P(`	"fmt"`)
	g.P(`	"unsafe"`)
	g.P(")")
	g.P()
	for _, hm := range hot {
		emitHotFunc(g, hm)
	}
}

// emitHotFunc writes one GodashHot_<Service>_<Method> function.
func emitHotFunc(g *protogen.GeneratedFile, hm hotMethod) {
	base := strings.TrimSuffix(hm.service.GoName, "Service")
	iface := base + "RPCHandler"
	funcName := "GodashHot_" + hm.service.GoName + "_" + hm.method.GoName
	reqType := hm.method.Input.GoIdent.GoName

	g.P("// ", funcName, " unpacks the packed request at reqPtr, calls the unary")
	g.P("// handler and packs the response into respPtr. It backs the")
	g.P("// `", hm.service.GoName, "_", hm.method.GoName, "` native FFI export; the web")
	g.P("// build uses the protobuf envelope instead.")
	g.P("func ", funcName, "(ctx context.Context, handler ", iface, ", reqPtr unsafe.Pointer, respPtr unsafe.Pointer) error {")
	g.P("\tvar req ", reqType)
	for _, f := range hm.req.Fields {
		pf := protogenField(hm.method.Input, f.Number)
		g.P("\treq.", pf.GoName, " = *(*", f.GoType, ")(unsafe.Add(reqPtr, ", f.Offset, "))")
	}
	if len(hm.req.Fields) == 0 {
		g.P("\t_ = unsafe.Pointer(reqPtr)")
	}
	g.P("\tresp, err := handler.", hm.method.GoName, "(ctx, &req)")
	g.P("\tif err != nil {")
	g.P("\t\treturn err")
	g.P("\t}")
	g.P("\tif resp == nil {")
	g.P("\t\treturn fmt.Errorf(\"hot handler ", hm.service.GoName, "_", hm.method.GoName, " returned a nil response\")")
	g.P("\t}")
	if len(hm.resp.Fields) == 0 {
		g.P("\t_ = resp")
		g.P("\t_ = unsafe.Pointer(respPtr)")
	}
	for _, f := range hm.resp.Fields {
		pf := protogenField(hm.method.Output, f.Number)
		g.P("\t*(*", f.GoType, ")(unsafe.Add(respPtr, ", f.Offset, ")) = resp.", pf.GoName)
	}
	g.P("\treturn nil")
	g.P("}")
	g.P()
}

// protogenField finds the protogen field with the given number.
func protogenField(m *protogen.Message, num protoreflect.FieldNumber) *protogen.Field {
	for _, f := range m.Fields {
		if f.Desc.Number() == num {
			return f
		}
	}
	return nil
}

// collectPushMessages returns messages whose name starts with "Push" (excluding "Push" itself).
func collectPushMessages(file *protogen.File) []*protogen.Message {
	var result []*protogen.Message
	for _, msg := range file.Messages {
		name := string(msg.Desc.Name())
		if strings.HasPrefix(name, "Push") && name != "Push" {
			result = append(result, msg)
		}
	}
	return result
}

// emitPushHelpers generates SendPushXxx functions for each Push-prefixed message.
func emitPushHelpers(g *protogen.GeneratedFile, pushMessages []*protogen.Message, alias string) {
	for _, msg := range pushMessages {
		msgName := msg.GoIdent.GoName
		fullName := string(msg.Desc.FullName())
		funcName := "Send" + msgName
		g.P("// ", funcName, " sends a ", msgName, " message to Dart as a fire-and-forget push.")
		g.P("func ", funcName, "(msg *", msgName, ") error {")
		g.P(`	if core.PushFn == nil {`)
		g.P(`		return fmt.Errorf("pushFn is not set")`)
		g.P(`	}`)
		g.P(`	return core.PushFn(&core.Push{Type: "`, fullName, `", Payload: core.MarshalHelper(msg)})`)
		g.P("}")
		g.P()
	}
}

// generateNormalService generates the server-side handler interface and router (Dart->Go).
func generateNormalService(g *protogen.GeneratedFile, service *protogen.Service, alias string) {
	serviceName := service.GoName
	baseName := strings.TrimSuffix(serviceName, "Service")
	interfaceName := baseName + "RPCHandler"
	handleFuncName := "Handle" + baseName + "RPC"

	g.P("// ", interfaceName, " is the server interface for the ", serviceName, " service.")
	g.P("type ", interfaceName, " interface {")
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() {
			continue
		}
		if method.Desc.IsStreamingServer() {
			g.P("\t", method.GoName, "(ctx context.Context, req *", method.Input.GoIdent.GoName, ", ch chan<- *core.Response) error")
		} else {
			g.P("\t", method.GoName, "(ctx context.Context, req *", method.Input.GoIdent.GoName, ") (*", method.Output.GoIdent.GoName, ", error)")
		}
	}
	g.P("}")
	g.P()

	g.P("func ", handleFuncName, "(ctx context.Context, req *core.RpcRequest, ch chan<- *core.Response, handler ", interfaceName, ") bool {")
	g.P("\tswitch req.Path {")
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() {
			continue
		}
		fullPath := fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name())
		g.P("\tcase ", `"`+fullPath+`"`, ":")
		g.P("\t\tvar msg ", method.Input.GoIdent.GoName)
		g.P("\t\tif err := msg.UnmarshalVT(req.Payload); err != nil {")
		g.P("\t\t\tch <- &core.Response{Responses: &core.Response_Error{Error: &core.Error{Code: 400, Message: err.Error()}}}")
		g.P("\t\t\treturn true")
		g.P("\t\t}")
		g.P()
		if method.Desc.IsStreamingServer() {
			g.P("\t\tif err := handler.", method.GoName, "(ctx, &msg, ch); err != nil {")
			g.P("\t\t\tch <- &core.Response{Responses: &core.Response_Error{Error: &core.Error{Code: 500, Message: err.Error()}}}")
			g.P("\t\t}")
		} else {
			g.P("\t\tresp, err := handler.", method.GoName, "(ctx, &msg)")
			g.P("\t\tif err != nil {")
			g.P("\t\t\tch <- &core.Response{Responses: &core.Response_Error{Error: &core.Error{Code: 500, Message: err.Error()}}}")
			g.P("\t\t} else {")
			g.P("\t\t\tch <- &core.Response{Responses: &core.Response_RpcResponse{RpcResponse: &core.RpcResponse{Payload: core.MarshalHelper(resp)}}}")
			g.P("\t\t}")
		}
		g.P("\t\treturn true")
	}
	g.P("\t}")
	g.P("\treturn false")
	g.P("}")
	g.P()
}

// generateReverseService generates the client-side caller (Go->Dart) using ReverseCall.
// Only unary methods are supported (no streaming from Go side).
func generateReverseService(g *protogen.GeneratedFile, service *protogen.Service, alias string) {
	serviceName := service.GoName

	g.P("// ", serviceName, "Caller contains generated ReverseCall helpers for ", serviceName, ".")
	g.P("// Each function sends a Push to Dart and waits for a ReverseResponse.")
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			continue // streaming not supported for ReverseService
		}
		fullPath := fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name())
		funcName := strings.TrimSuffix(serviceName, "ReverseService") + "ReverseRPC" + method.GoName
		inName := method.Input.GoIdent.GoName
		outName := method.Output.GoIdent.GoName

		g.P("func ", funcName, "(ctx context.Context, req *", inName, ") (*", outName, ", error) {")
		g.P(`	push := &core.Push{Type: "`, fullPath, `", Payload: core.MarshalHelper(req)}`)
		g.P("\tpayload, err := core.ReverseCallFn(ctx, push)")
		g.P("\tif err != nil {")
		g.P("\t\treturn nil, err")
		g.P("\t}")
		g.P("\tvar resp ", outName)
		g.P("\tif err := resp.UnmarshalVT(payload); err != nil {")
		g.P("\t\treturn nil, err")
		g.P("\t}")
		g.P("\treturn &resp, nil")
		g.P("}")
		g.P()
	}
}
