package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"

	"github.com/nosuta/godash/internal/hotlayout"
	godashpb "github.com/nosuta/godash/pb"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	pushMessages := collectPushMessages(file)
	hasPush := len(pushMessages) > 0

	var normalServices, reverseServices []*protogen.Service
	for _, svc := range file.Services {
		if strings.HasSuffix(string(svc.Desc.Name()), "ReverseService") {
			reverseServices = append(reverseServices, svc)
		} else {
			normalServices = append(normalServices, svc)
		}
	}

	if len(normalServices) == 0 && len(reverseServices) == 0 && !hasPush {
		return
	}

	basename := file.GeneratedFilenamePrefix
	idx := strings.LastIndex(basename, "/")
	if idx != -1 {
		basename = basename[idx+1:]
	}
	filename := basename + ".flap.dart"

	g := gen.NewGeneratedFile(filename, "")

	g.P("// Code generated by protoc-gen-dart-godash. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()

	hasHot := false
	for _, svc := range normalServices {
		if len(hotMethodsFor(svc)) > 0 {
			hasHot = true
			break
		}
	}

	if hasPush || len(reverseServices) > 0 {
		g.P("import 'dart:async';")
	}
	if hasHot {
		g.P("import 'dart:typed_data';")
	}
	if hasPush || len(reverseServices) > 0 || hasHot {
		g.P()
	}
	needsBridge := len(reverseServices) > 0 || hasPush
	if needsBridge {
		g.P("import 'package:godash/bridge/bridge.dart';")
	}
	if len(normalServices) > 0 {
		g.P("import 'package:godash/bridge/transport.dart';")
	}
	if len(reverseServices) > 0 || hasPush {
		g.P("import 'package:fixnum/fixnum.dart';")
	}

	dartProtoImport := fmt.Sprintf("import '%s.pb.dart';", basename)
	g.P(dartProtoImport)

	importCount := file.Desc.Imports().Len()
	for i := 0; i < importCount; i++ {
		dep := file.Desc.Imports().Get(i)
		// The godash option definitions are only used at code-generation time
		// and are not generated as Dart; importing them would reference a
		// missing options.pb.dart.
		if strings.HasPrefix(dep.Path(), "godash/") {
			continue
		}
		depPath := strings.TrimSuffix(dep.Path(), ".proto")
		idx = strings.LastIndex(depPath, "/")
		if idx != -1 {
			depPath = depPath[idx+1:]
		}
		g.P("import '", depPath, ".pb.dart';")
	}

	if hasPush || len(reverseServices) > 0 {
		g.P("import 'package:godash/pb/core.pb.dart';")
	}

	g.P()

	for _, svc := range normalServices {
		generateNormalServiceClient(g, svc)
	}

	for _, svc := range reverseServices {
		generateReverseServiceHandler(g, svc)
	}

	if hasPush {
		generatePushHandler(g, basename, pushMessages)
	}
}

// collectPushMessages returns messages whose name starts with "Push" (excluding "Push" itself).
func collectPushMessages(file *protogen.File) []*protogen.Message {
	var result []*protogen.Message
	for _, msg := range file.Messages {
		name := string(msg.Desc.Name())
		if strings.HasPrefix(name, "Push") && name != "Push" {
			result = append(result, msg)
		}
	}
	return result
}

func generatePushHandler(g *protogen.GeneratedFile, basename string, pushMessages []*protogen.Message) {
	g.P("/// PushHandler dispatches incoming fire-and-forget [Push] messages to typed streams.")
	g.P("/// Instantiate once and reuse — call dispose() when done.")
	g.P("class PushHandler {")
	g.P("  late final StreamSubscription<Push> _subscription;")
	g.P()

	for _, msg := range pushMessages {
		msgName := msg.GoIdent.GoName
		fieldSuffix := strings.TrimPrefix(msgName, "Push")
		controllerName := "_" + strings.ToLower(fieldSuffix[:1]) + fieldSuffix[1:] + "Controller"
		g.P("  final _StreamBroadcast<", msgName, "> ", controllerName, " = _StreamBroadcast();")
	}

	g.P()
	g.P("  PushHandler() {")
	g.P("    _subscription = Bridge().push.listen(_dispatch);")
	g.P("  }")
	g.P()

	for _, msg := range pushMessages {
		msgName := msg.GoIdent.GoName
		fieldSuffix := strings.TrimPrefix(msgName, "Push")
		streamName := strings.ToLower(fieldSuffix[:1]) + fieldSuffix[1:]
		controllerName := "_" + streamName + "Controller"
		g.P("  Stream<", msgName, "> get ", streamName, " => ", controllerName, ".stream;")
	}

	g.P()
	g.P("  void _dispatch(Push push) {")
	g.P("    if (push.reversePort != Int64.ZERO) return;")
	g.P("    switch (push.type) {")
	for _, msg := range pushMessages {
		msgName := msg.GoIdent.GoName
		fullName := string(msg.Desc.FullName())
		fieldSuffix := strings.TrimPrefix(msgName, "Push")
		streamName := strings.ToLower(fieldSuffix[:1]) + fieldSuffix[1:]
		controllerName := "_" + streamName + "Controller"
		g.P("      case '", fullName, "':")
		g.P("        ", controllerName, ".add(", msgName, ".fromBuffer(push.payload));")
		g.P("        break;")
	}
	g.P("      default:")
	g.P("        break;")
	g.P("    }")
	g.P("  }")

	g.P()
	g.P("  void dispose() {")
	g.P("    _subscription.cancel();")
	for _, msg := range pushMessages {
		msgName := msg.GoIdent.GoName
		fieldSuffix := strings.TrimPrefix(msgName, "Push")
		controllerName := "_" + strings.ToLower(fieldSuffix[:1]) + fieldSuffix[1:] + "Controller"
		_ = msgName
		g.P("    ", controllerName, ".close();")
	}
	g.P("  }")
	g.P("}")
	g.P()
	g.P("class _StreamBroadcast<T> {")
	g.P("  final _controller = StreamController<T>.broadcast();")
	g.P("  Stream<T> get stream => _controller.stream;")
	g.P("  void add(T value) => _controller.add(value);")
	g.P("  void close() => _controller.close();")
	g.P("}")
}

// generateReverseServiceHandler generates a self-contained abstract class.
// The constructor subscribes to Bridge().push and handles its own paths,
// so the implementor just needs to instantiate the subclass.
// generateReverseServiceHandler generates a self-contained abstract class.
// The constructor subscribes to Bridge().push and handles its own paths,
// so the implementor just needs to instantiate the subclass.
func generateReverseServiceHandler(g *protogen.GeneratedFile, service *protogen.Service) {
	baseName := strings.TrimSuffix(service.GoName, "Service")
	handlerName := baseName + "Rpc"
	noopName := "_" + baseName + "RpcNoOp"
	globalVar := "_" + toCamelCase(baseName) + "Rpc"

	// collect unary methods only
	var methods []*protogen.Method
	for _, m := range service.Methods {
		if !m.Desc.IsStreamingClient() && !m.Desc.IsStreamingServer() {
			methods = append(methods, m)
		}
	}

	g.P("/// ", handlerName, " handles Go->Dart->Go calls for ", service.GoName, ".")
	g.P("/// Extend this class and implement the abstract methods.")
	g.P("/// Instantiating the subclass is all that is needed — it self-registers,")
	g.P("/// automatically disposing the previous handler.")
	g.P("abstract class ", handlerName, " {")
	g.P("  late final Bridge _bridge;")
	g.P("  StreamSubscription<Push>? _subscription;")
	g.P()
	g.P("  ", handlerName, "() {")
	g.P("    _bridge = Bridge();")
	g.P("    ", globalVar, ".dispose();")
	g.P("    ", globalVar, " = this;")
	g.P("    _subscription = _bridge.push.listen(_dispatch);")
	g.P("  }")
	g.P()
	g.P("  // Internal constructor for no-op — skips registration and Bridge().")
	g.P("  ", handlerName, "._noOp();")
	g.P()

	for _, m := range methods {
		inName := m.Input.GoIdent.GoName
		outName := m.Output.GoIdent.GoName
		g.P("  Future<", outName, "> ", toCamelCase(m.GoName), "(", inName, " request);")
	}

	g.P()
	g.P("  void dispose() => _subscription?.cancel();")
	g.P()
	g.P("  void _dispatch(Push push) {")
	g.P("    if (push.reversePort == Int64.ZERO) return;")
	g.P("    Future<List<int>>? fut;")
	g.P("    switch (push.type) {")
	for _, m := range methods {
		fullPath := fmt.Sprintf("/%s/%s", service.Desc.FullName(), m.Desc.Name())
		inName := m.Input.GoIdent.GoName
		g.P("      case '", fullPath, "':")
		g.P("        fut = ", toCamelCase(m.GoName), "(", inName, ".fromBuffer(push.payload))")
		g.P("            .then((r) => r.writeToBuffer());")
		g.P("        break;")
	}
	g.P("    }")
	g.P("    if (fut == null) return;")
	g.P("    fut.then((payload) => _bridge.sendReverseResponse(push.reversePort, payload))")
	g.P("        .catchError((_) => _bridge.sendReverseResponse(push.reversePort, []));")
	g.P("  }")
	g.P("}")
	g.P()

	// no-op — does not call super, holds no subscription, dispose() is a no-op.
	// Stored as the initial value of the global so the real handler can call dispose() safely.
	g.P("class ", noopName, " extends ", handlerName, " {")
	g.P("  // Bypasses super constructor — no Bridge(), no subscription.")
	g.P("  ", noopName, "._() : super._noOp();")
	for _, m := range methods {
		outName := m.Output.GoIdent.GoName
		inName := m.Input.GoIdent.GoName
		g.P("  @override")
		g.P("  Future<", outName, "> ", toCamelCase(m.GoName), "(", inName, " request) async => ", outName, "();")
	}
	g.P("  @override")
	g.P("  void _dispatch(Push push) {} // no-op")
	g.P("}")
	g.P()
	g.P("// Global singleton — starts as no-op, replaced when a real handler is instantiated.")
	g.P("// ignore: prefer_final_fields")
	g.P(handlerName, " ", globalVar, " = ", noopName, "._();")
	g.P()
}

// generateNormalServiceClient generates the Dart client for a normal (Dart->Go) service.
func generateNormalServiceClient(g *protogen.GeneratedFile, service *protogen.Service) {
	baseName := strings.TrimSuffix(service.GoName, "Service")
	clientName := baseName + "RpcClient"

	hot := map[protoreflect.Name]hotMethod{}
	for _, hm := range hotMethodsFor(service) {
		hot[hm.method.Desc.Name()] = hm
	}

	g.P("class ", clientName, " {")
	g.P("  final Transport _transport;")
	g.P()
	g.P("  ", clientName, "() : _transport = Transport();")
	g.P()

	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() {
			continue
		}

		reqName := method.Input.GoIdent.GoName
		resName := method.Output.GoIdent.GoName
		methodName := toCamelCase(method.GoName)
		fullPath := fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name())

		if hm, ok := hot[method.Desc.Name()]; ok {
			emitHotClientMethod(g, service, hm, clientName, reqName, resName, methodName, fullPath)
			continue
		}

		if method.Desc.IsStreamingServer() {
			g.P("  Stream<", resName, "> ", methodName, "(", reqName, " request) async* {")
			g.P("    yield* _transport.stream(")
			g.P("      '", fullPath, "',")
			g.P("      request,")
			g.P("      () => ", resName, "(),")
			g.P("    );")
			g.P("  }")
			g.P()
		} else {
			g.P("  Future<", resName, "> ", methodName, "(", reqName, " request) async {")
			g.P("    return _transport.unary(")
			g.P("      '", fullPath, "',")
			g.P("      request,")
			g.P("      () => ", resName, "(),")
			g.P("    );")
			g.P("  }")
			g.P()
		}
	}
	g.P("}")
}

// hotMethod is a unary method whose messages are packable and that carries the
// (godash.hot) option.
type hotMethod struct {
	method *protogen.Method
	req    hotlayout.Layout
	resp   hotlayout.Layout
}

// isHot reports whether the method carries the `(godash.hot) = true` option.
func isHot(m *protogen.Method) bool {
	opts := m.Desc.Options()
	if opts == nil {
		return false
	}
	v, _ := proto.GetExtension(opts, godashpb.E_Hot).(bool)
	return v
}

// hotMethodsFor returns the packable hot methods of a service. Streaming or
// non-packable methods are omitted and keep the envelope path.
func hotMethodsFor(service *protogen.Service) []hotMethod {
	var out []hotMethod
	for _, m := range service.Methods {
		if m.Desc.IsStreamingClient() || m.Desc.IsStreamingServer() {
			continue
		}
		if !isHot(m) {
			continue
		}
		req, err := hotlayout.Compute(m.Input.Desc)
		if err != nil {
			continue
		}
		resp, err := hotlayout.Compute(m.Output.Desc)
		if err != nil {
			continue
		}
		out = append(out, hotMethod{method: m, req: req, resp: resp})
	}
	return out
}

// emitHotClientMethod writes a typed client method that uses the packed FFI
// fast path on native and falls back to the protobuf envelope on web.
func emitHotClientMethod(
	g *protogen.GeneratedFile,
	service *protogen.Service,
	hm hotMethod,
	clientName, reqName, resName, methodName, fullPath string,
) {
	symbol := service.GoName + "_" + hm.method.GoName
	privateName := "_" + methodName + "Hot"

	g.P("  /// Hot path: packed-struct FFI on native, protobuf envelope on web.")
	g.P("  Future<", resName, "> ", methodName, "(", reqName, " request) {")
	g.P("    if (!_transport.supportsHotPath) {")
	g.P("      return _transport.unary(")
	g.P("        '", fullPath, "',")
	g.P("        request,")
	g.P("        () => ", resName, "(),")
	g.P("      );")
	g.P("    }")
	g.P("    return Future.sync(() => ", privateName, "(request));")
	g.P("  }")
	g.P()
	g.P("  ", resName, " ", privateName, "(", reqName, " request) {")
	g.P("    final reqBytes = Uint8List(", hm.req.Size, ");")
	if len(hm.req.Fields) > 0 {
		g.P("    final reqView = ByteData.sublistView(reqBytes);")
	}
	for _, f := range hm.req.Fields {
		_, set, isBool := dartAccessor(f.GoType)
		name := dartFieldName(f.Desc.Name())
		if isBool {
			g.P("    reqView.setUint8(", f.Offset, ", request.", name, " ? 1 : 0);")
			continue
		}
		g.P("    reqView.", set, "(", f.Offset, ", request.", name, ", Endian.host);")
	}
	g.P("    final respBytes = _transport.hotRaw('", symbol, "', reqBytes, ", hm.resp.Size, ");")
	if len(hm.resp.Fields) > 0 {
		g.P("    final respView = ByteData.sublistView(respBytes);")
	}
	g.P("    final output = ", resName, "();")
	for _, f := range hm.resp.Fields {
		get, _, isBool := dartAccessor(f.GoType)
		name := dartFieldName(f.Desc.Name())
		if isBool {
			g.P("    output.", name, " = respView.getUint8(", f.Offset, ") != 0;")
			continue
		}
		g.P("    output.", name, " = respView.", get, "(", f.Offset, ", Endian.host);")
	}
	g.P("    return output;")
	g.P("  }")
	g.P()
}

// dartAccessor maps a packed Go scalar type to the ByteData getter/setter pair.
func dartAccessor(goType string) (get, set string, isBool bool) {
	switch goType {
	case "int32":
		return "getInt32", "setInt32", false
	case "uint32":
		return "getUint32", "setUint32", false
	case "int64":
		return "getInt64", "setInt64", false
	case "uint64":
		return "getUint64", "setUint64", false
	case "float32":
		return "getFloat32", "setFloat32", false
	case "float64":
		return "getFloat64", "setFloat64", false
	case "bool":
		return "getUint8", "setUint8", true
	}
	return "", "", false
}

// dartFieldName converts a proto field name (lower_snake) to the Dart getter
// name emitted by protoc-gen-dart (lowerCamel).
func dartFieldName(name protoreflect.Name) string {
	parts := strings.Split(string(name), "_")
	out := parts[0]
	for _, p := range parts[1:] {
		if p == "" {
			continue
		}
		out += strings.ToUpper(p[:1]) + p[1:]
	}
	return out
}

// protogenField finds the protogen field with the given number.
func protogenField(m *protogen.Message, num protoreflect.FieldNumber) *protogen.Field {
	for _, f := range m.Fields {
		if f.Desc.Number() == num {
			return f
		}
	}
	return nil
}

func toCamelCase(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
