package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func sampleHot() []hotInfo {
	return []hotInfo{
		{Name: "CalcService_Add", ServerVar: "calcServer"},
		{Name: "EchoService_Ping", ServerVar: "echoServer"},
	}
}

func TestRenderHotHandlerWithMethods(t *testing.T) {
	got := renderHotHandler(moduleInfo{Name: "flap", PbAlias: "flappb"}, sampleHot())
	for _, want := range []string{
		"//go:build !js",
		"func HotInvoke(",
		`case "CalcService_Add":`,
		"flappb.GodashHot_CalcService_Add(ctx, calcServer, reqPtr, respPtr)",
		`case "EchoService_Ping":`,
		"flappb.GodashHot_EchoService_Ping(ctx, echoServer, reqPtr, respPtr)",
		`flappb "flap/pb"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("renderHotHandler missing %q\n---\n%s", want, got)
		}
	}
}

func TestRenderHotHandlerWithoutMethods(t *testing.T) {
	got := renderHotHandler(moduleInfo{Name: "flap", PbAlias: "flappb"}, nil)
	if !strings.Contains(got, "//go:build !js") {
		t.Errorf("missing build tag:\n%s", got)
	}
	if strings.Contains(got, "flap/pb") {
		t.Errorf("no hot methods should not import the project pb package:\n%s", got)
	}
	if !strings.Contains(got, `return fmt.Errorf("hot method not found: %s", name)`) {
		t.Errorf("missing not-found error:\n%s", got)
	}
}

func TestRenderMainGoIncludesHotExports(t *testing.T) {
	got := renderMainGo(moduleInfo{Name: "flap"}, sampleHot())
	for _, want := range []string{
		"//export CalcService_Add",
		"func CalcService_Add(req unsafe.Pointer, resp unsafe.Pointer) C.int32_t",
		`flaprpc.HotInvoke(context.Background(), "CalcService_Add", req, resp)`,
		"//export EchoService_Ping",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("renderMainGo missing %q", want)
		}
	}
	plain := renderMainGo(moduleInfo{Name: "flap"}, nil)
	if strings.Contains(plain, "//export CalcService_Add") {
		t.Error("renderMainGo must not emit hot exports without hot methods")
	}
}

func TestScanHotMethods(t *testing.T) {
	dir := t.TempDir()
	content := `// Code generated by protoc-gen-go-godash. DO NOT EDIT.

//go:build !js

package pb

import "context"

func GodashHot_CalcService_Add(ctx context.Context, handler CalcRPCHandler, reqPtr unsafe.Pointer, respPtr unsafe.Pointer) error {
	return nil
}
`
	if err := os.WriteFile(filepath.Join(dir, "calc.hot.go"), []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
	services := []serviceInfo{
		{Name: "Calc", HandlerIface: "CalcRPCHandler", ServerVar: "calcServer"},
	}
	got, err := scanHotMethods(dir, services)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 {
		t.Fatalf("got %d hot methods, want 1: %+v", len(got), got)
	}
	if got[0].Name != "CalcService_Add" || got[0].ServerVar != "calcServer" {
		t.Fatalf("unexpected hot info: %+v", got[0])
	}
}
