// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int InitializeDartAPI(ffi.Pointer<ffi.Void> api) {
    return _InitializeDartAPI(api);
  }

  late final _InitializeDartAPIPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<ffi.Void>)>>(
        'InitializeDartAPI',
      );
  late final _InitializeDartAPI =
      _InitializeDartAPIPtr.asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void RPC(int port, ffi.Pointer<BytesContainer> payload) {
    return _RPC(port, payload);
  }

  late final _RPCPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<BytesContainer>)
        >
      >('RPC');
  late final _RPC =
      _RPCPtr.asFunction<void Function(int, ffi.Pointer<BytesContainer>)>();

  void FreeBytesContainer(ffi.Pointer<BytesContainer> payload) {
    return _FreeBytesContainer(payload);
  }

  late final _FreeBytesContainerPtr = _lookup<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<BytesContainer>)>
  >('FreeBytesContainer');
  late final _FreeBytesContainer =
      _FreeBytesContainerPtr.asFunction<
        void Function(ffi.Pointer<BytesContainer>)
      >();

  ffi.Pointer<BytesContainer> CallSync(ffi.Pointer<BytesContainer> payload) {
    return _CallSync(payload);
  }

  late final _CallSyncPtr = _lookup<
    ffi.NativeFunction<
      ffi.Pointer<BytesContainer> Function(ffi.Pointer<BytesContainer>)
    >
  >('CallSync');
  late final _CallSync =
      _CallSyncPtr.asFunction<
        ffi.Pointer<BytesContainer> Function(ffi.Pointer<BytesContainer>)
      >();
}

final class __mbstate_t extends ffi.Union {
  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> __mbstate8;

  @ffi.LongLong()
  external int _mbstateL;
}

final class sigval extends ffi.Union {
  @ffi.Int()
  external int sival_int;

  external ffi.Pointer<ffi.Void> sival_ptr;
}

final class __siginfo extends ffi.Struct {
  @ffi.Int()
  external int si_signo;

  @ffi.Int()
  external int si_errno;

  @ffi.Int()
  external int si_code;

  @ffi.Int()
  external int si_pid;

  @ffi.UnsignedInt()
  external int si_uid;

  @ffi.Int()
  external int si_status;

  external ffi.Pointer<ffi.Void> si_addr;

  external sigval si_value;

  @ffi.Long()
  external int si_band;

  @ffi.Array.multi([7])
  external ffi.Array<ffi.UnsignedLong> __pad;
}

final class __sigaction_u extends ffi.Union {
  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>
  __sa_handler;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Int, ffi.Pointer<__siginfo>, ffi.Pointer<ffi.Void>)
    >
  >
  __sa_sigaction;
}

final class wait extends ffi.Opaque {}

final class bytesContainer extends ffi.Struct {
  external ffi.Pointer<ffi.Void> message;

  @ffi.Int()
  external int size;
}

typedef BytesContainer = bytesContainer;
