// Code as template. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: core.proto

//go:build !js

// Dart package name

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Cancel
type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int64                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *Cancel) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Cancel) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Cancel) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Done
type Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *Done) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Done) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Init
type Init struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PushPort         int64                  `protobuf:"varint,1,opt,name=push_port,json=pushPort,proto3" json:"push_port,omitempty"`
	TempDir          string                 `protobuf:"bytes,2,opt,name=temp_dir,json=tempDir,proto3" json:"temp_dir,omitempty"`
	SupportDir       string                 `protobuf:"bytes,3,opt,name=support_dir,json=supportDir,proto3" json:"support_dir,omitempty"`
	DocumentsDir     string                 `protobuf:"bytes,4,opt,name=documents_dir,json=documentsDir,proto3" json:"documents_dir,omitempty"`
	AppEncryptionKey string                 `protobuf:"bytes,5,opt,name=app_encryption_key,json=appEncryptionKey,proto3" json:"app_encryption_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Init) Reset() {
	*x = Init{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Init) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Init) ProtoMessage() {}

func (x *Init) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Init.ProtoReflect.Descriptor instead.
func (*Init) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *Init) GetPushPort() int64 {
	if x != nil {
		return x.PushPort
	}
	return 0
}

func (x *Init) GetTempDir() string {
	if x != nil {
		return x.TempDir
	}
	return ""
}

func (x *Init) GetSupportDir() string {
	if x != nil {
		return x.SupportDir
	}
	return ""
}

func (x *Init) GetDocumentsDir() string {
	if x != nil {
		return x.DocumentsDir
	}
	return ""
}

func (x *Init) GetAppEncryptionKey() string {
	if x != nil {
		return x.AppEncryptionKey
	}
	return ""
}

// ReverseResponse is sent by Dart to Go as a reply to a Go->Dart->Go ReverseService call.
type ReverseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReversePort   int64                  `protobuf:"varint,1,opt,name=reverse_port,json=reversePort,proto3" json:"reverse_port,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseResponse) Reset() {
	*x = ReverseResponse{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseResponse) ProtoMessage() {}

func (x *ReverseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseResponse.ProtoReflect.Descriptor instead.
func (*ReverseResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *ReverseResponse) GetReversePort() int64 {
	if x != nil {
		return x.ReversePort
	}
	return 0
}

func (x *ReverseResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Request
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Port  int64                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	// Types that are valid to be assigned to Requests:
	//
	//	*Request_Init
	//	*Request_Cancel
	//	*Request_RpcRequest
	//	*Request_ReverseResponse
	Requests      isRequest_Requests `protobuf_oneof:"requests"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *Request) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Request) GetRequests() isRequest_Requests {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *Request) GetInit() *Init {
	if x != nil {
		if x, ok := x.Requests.(*Request_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *Request) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Requests.(*Request_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *Request) GetRpcRequest() *RpcRequest {
	if x != nil {
		if x, ok := x.Requests.(*Request_RpcRequest); ok {
			return x.RpcRequest
		}
	}
	return nil
}

func (x *Request) GetReverseResponse() *ReverseResponse {
	if x != nil {
		if x, ok := x.Requests.(*Request_ReverseResponse); ok {
			return x.ReverseResponse
		}
	}
	return nil
}

type isRequest_Requests interface {
	isRequest_Requests()
}

type Request_Init struct {
	Init *Init `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type Request_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

type Request_RpcRequest struct {
	RpcRequest *RpcRequest `protobuf:"bytes,10,opt,name=rpc_request,json=rpcRequest,proto3,oneof"`
}

type Request_ReverseResponse struct {
	ReverseResponse *ReverseResponse `protobuf:"bytes,11,opt,name=reverse_response,json=reverseResponse,proto3,oneof"`
}

func (*Request_Init) isRequest_Requests() {}

func (*Request_Cancel) isRequest_Requests() {}

func (*Request_RpcRequest) isRequest_Requests() {}

func (*Request_ReverseResponse) isRequest_Requests() {}

// Response
type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Responses:
	//
	//	*Response_Error
	//	*Response_Done
	//	*Response_Push
	//	*Response_RpcResponse
	Responses     isResponse_Responses `protobuf_oneof:"responses"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

func (x *Response) GetResponses() isResponse_Responses {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *Response) GetError() *Error {
	if x != nil {
		if x, ok := x.Responses.(*Response_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Response) GetDone() *Done {
	if x != nil {
		if x, ok := x.Responses.(*Response_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *Response) GetPush() *Push {
	if x != nil {
		if x, ok := x.Responses.(*Response_Push); ok {
			return x.Push
		}
	}
	return nil
}

func (x *Response) GetRpcResponse() *RpcResponse {
	if x != nil {
		if x, ok := x.Responses.(*Response_RpcResponse); ok {
			return x.RpcResponse
		}
	}
	return nil
}

type isResponse_Responses interface {
	isResponse_Responses()
}

type Response_Error struct {
	Error *Error `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type Response_Done struct {
	Done *Done `protobuf:"bytes,6,opt,name=done,proto3,oneof"`
}

type Response_Push struct {
	Push *Push `protobuf:"bytes,7,opt,name=push,proto3,oneof"`
}

type Response_RpcResponse struct {
	RpcResponse *RpcResponse `protobuf:"bytes,10,opt,name=rpc_response,json=rpcResponse,proto3,oneof"`
}

func (*Response_Error) isResponse_Responses() {}

func (*Response_Done) isResponse_Responses() {}

func (*Response_Push) isResponse_Responses() {}

func (*Response_RpcResponse) isResponse_Responses() {}

// RpcRequest
type RpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7}
}

func (x *RpcRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RpcRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// RpcResponse
type RpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8}
}

func (x *RpcResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Push
type Push struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Type    string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// reverse_port is set when Go requests a response from Dart (Go->Dart->Go ReverseService).
	// 0 means fire-and-forget.
	ReversePort   int64 `protobuf:"varint,3,opt,name=reverse_port,json=reversePort,proto3" json:"reverse_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Push) Reset() {
	*x = Push{}
	mi := &file_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Push) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Push) ProtoMessage() {}

func (x *Push) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Push.ProtoReflect.Descriptor instead.
func (*Push) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{9}
}

func (x *Push) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Push) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Push) GetReversePort() int64 {
	if x != nil {
		return x.ReversePort
	}
	return 0
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\x02pb\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"\x06Cancel\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x03R\x04port\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x04Done\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb2\x01\n" +
	"\x04Init\x12\x1b\n" +
	"\tpush_port\x18\x01 \x01(\x03R\bpushPort\x12\x19\n" +
	"\btemp_dir\x18\x02 \x01(\tR\atempDir\x12\x1f\n" +
	"\vsupport_dir\x18\x03 \x01(\tR\n" +
	"supportDir\x12#\n" +
	"\rdocuments_dir\x18\x04 \x01(\tR\fdocumentsDir\x12,\n" +
	"\x12app_encryption_key\x18\x05 \x01(\tR\x10appEncryptionKey\"N\n" +
	"\x0fReverseResponse\x12!\n" +
	"\freverse_port\x18\x01 \x01(\x03R\vreversePort\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\xe4\x01\n" +
	"\aRequest\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x03R\x04port\x12\x1e\n" +
	"\x04init\x18\x01 \x01(\v2\b.pb.InitH\x00R\x04init\x12$\n" +
	"\x06cancel\x18\x04 \x01(\v2\n" +
	".pb.CancelH\x00R\x06cancel\x121\n" +
	"\vrpc_request\x18\n" +
	" \x01(\v2\x0e.pb.RpcRequestH\x00R\n" +
	"rpcRequest\x12@\n" +
	"\x10reverse_response\x18\v \x01(\v2\x13.pb.ReverseResponseH\x00R\x0freverseResponseB\n" +
	"\n" +
	"\brequests\"\xb0\x01\n" +
	"\bResponse\x12!\n" +
	"\x05error\x18\x01 \x01(\v2\t.pb.ErrorH\x00R\x05error\x12\x1e\n" +
	"\x04done\x18\x06 \x01(\v2\b.pb.DoneH\x00R\x04done\x12\x1e\n" +
	"\x04push\x18\a \x01(\v2\b.pb.PushH\x00R\x04push\x124\n" +
	"\frpc_response\x18\n" +
	" \x01(\v2\x0f.pb.RpcResponseH\x00R\vrpcResponseB\v\n" +
	"\tresponses\":\n" +
	"\n" +
	"RpcRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"'\n" +
	"\vRpcResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"W\n" +
	"\x04Push\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12!\n" +
	"\freverse_port\x18\x03 \x01(\x03R\vreversePortB Z\x1egithub.com/nosuta/godash/v2/pbb\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_core_proto_goTypes = []any{
	(*Error)(nil),           // 0: pb.Error
	(*Cancel)(nil),          // 1: pb.Cancel
	(*Done)(nil),            // 2: pb.Done
	(*Init)(nil),            // 3: pb.Init
	(*ReverseResponse)(nil), // 4: pb.ReverseResponse
	(*Request)(nil),         // 5: pb.Request
	(*Response)(nil),        // 6: pb.Response
	(*RpcRequest)(nil),      // 7: pb.RpcRequest
	(*RpcResponse)(nil),     // 8: pb.RpcResponse
	(*Push)(nil),            // 9: pb.Push
}
var file_core_proto_depIdxs = []int32{
	3, // 0: pb.Request.init:type_name -> pb.Init
	1, // 1: pb.Request.cancel:type_name -> pb.Cancel
	7, // 2: pb.Request.rpc_request:type_name -> pb.RpcRequest
	4, // 3: pb.Request.reverse_response:type_name -> pb.ReverseResponse
	0, // 4: pb.Response.error:type_name -> pb.Error
	2, // 5: pb.Response.done:type_name -> pb.Done
	9, // 6: pb.Response.push:type_name -> pb.Push
	8, // 7: pb.Response.rpc_response:type_name -> pb.RpcResponse
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	file_core_proto_msgTypes[5].OneofWrappers = []any{
		(*Request_Init)(nil),
		(*Request_Cancel)(nil),
		(*Request_RpcRequest)(nil),
		(*Request_ReverseResponse)(nil),
	}
	file_core_proto_msgTypes[6].OneofWrappers = []any{
		(*Response_Error)(nil),
		(*Response_Done)(nil),
		(*Response_Push)(nil),
		(*Response_RpcResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
