// Code as template. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: godash/options.proto

// godash options namespace. Import this file and use `option (godash.hot) = true;`
// on a unary method whose request/response messages contain only fixed-layout
// scalar fields to opt the method into the packed-struct hot path.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_godash_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "godash.hot",
		Tag:           "varint,50001,opt,name=hot",
		Filename:      "godash/options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// hot marks a unary method as eligible for the packed-struct FFI fast path.
	// The method falls back to the normal envelope path when the request or
	// response message cannot be packed (strings, bytes, nested messages,
	// repeated/map fields, explicit presence or oneofs).
	//
	// optional bool hot = 50001;
	E_Hot = &file_godash_options_proto_extTypes[0]
)

var File_godash_options_proto protoreflect.FileDescriptor

const file_godash_options_proto_rawDesc = "" +
	"\n" +
	"\x14godash/options.proto\x12\x06godash\x1a google/protobuf/descriptor.proto:2\n" +
	"\x03hot\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\bR\x03hotB\x1dZ\x1bgithub.com/nosuta/godash/pbb\x06proto3"

var file_godash_options_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
}
var file_godash_options_proto_depIdxs = []int32{
	0, // 0: godash.hot:extendee -> google.protobuf.MethodOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_godash_options_proto_init() }
func file_godash_options_proto_init() {
	if File_godash_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_godash_options_proto_rawDesc), len(file_godash_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_godash_options_proto_goTypes,
		DependencyIndexes: file_godash_options_proto_depIdxs,
		ExtensionInfos:    file_godash_options_proto_extTypes,
	}.Build()
	File_godash_options_proto = out.File
	file_godash_options_proto_goTypes = nil
	file_godash_options_proto_depIdxs = nil
}
